site_name: ReX Wiki
plugins:
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
theme:
  logo: assets/redot.png
  name: material
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
  palette:
    scheme: slate
    primary: deep-orange