site_name: ReX Wiki
plugins:
  - meta
  - info
markdown_extensions:
  - attr_list
  - md_in_html
theme:
  logo: assets/redot.png
  name: material
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
  palette:
    scheme: slate
    primary: deep-orange